org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
forge_version=47.0.3
immersive_aircraft_version=1.3.3+1.20.1+forge
immersive_aircraft_use_local=true

mod_id=immersive_aircraft_cruise
mod_name=Immersive_Aircraft_Modernization
mod_version=0.2.0
mod_group_id=com.g1739.immersiveaircraftcruise
mod_authors=交错次元
mod_license=All Rights Reserved
mod_description=Adds a modern overclocked cruise guidance module for Immersive Aircraft, with route editing, auto navigation, HUD fuel display, and landing modes.
